
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IConsultaVoos", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IConsultaVoos {


    /**
     * 
     * @param pagina
     * @param exibirFinalizados
     * @param icao
     * @param registrosPagina
     * @param idioma
     * @param partida
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarVoosSentido", action = "http://tempuri.org/ConsultarVoosSentido")
    @WebResult(name = "ConsultarVoosSentidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarVoosSentido", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVoosSentido")
    @ResponseWrapper(localName = "ConsultarVoosSentidoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVoosSentidoResponse")
    public String consultarVoosSentido(
        @WebParam(name = "icao", targetNamespace = "http://tempuri.org/")
        String icao,
        @WebParam(name = "idioma", targetNamespace = "http://tempuri.org/")
        String idioma,
        @WebParam(name = "partida", targetNamespace = "http://tempuri.org/")
        Boolean partida,
        @WebParam(name = "exibirFinalizados", targetNamespace = "http://tempuri.org/")
        Boolean exibirFinalizados,
        @WebParam(name = "registrosPagina", targetNamespace = "http://tempuri.org/")
        Integer registrosPagina,
        @WebParam(name = "pagina", targetNamespace = "http://tempuri.org/")
        Integer pagina);

    /**
     * 
     * @param pagina
     * @param exibirFinalizados
     * @param icao
     * @param registrosPagina
     * @param siglaCiaAerea
     * @param idioma
     * @param partida
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarVoosCiaAerea", action = "http://tempuri.org/ConsultarVoosCiaAerea")
    @WebResult(name = "ConsultarVoosCiaAereaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarVoosCiaAerea", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVoosCiaAerea")
    @ResponseWrapper(localName = "ConsultarVoosCiaAereaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVoosCiaAereaResponse")
    public String consultarVoosCiaAerea(
        @WebParam(name = "icao", targetNamespace = "http://tempuri.org/")
        String icao,
        @WebParam(name = "idioma", targetNamespace = "http://tempuri.org/")
        String idioma,
        @WebParam(name = "partida", targetNamespace = "http://tempuri.org/")
        Boolean partida,
        @WebParam(name = "siglaCiaAerea", targetNamespace = "http://tempuri.org/")
        String siglaCiaAerea,
        @WebParam(name = "exibirFinalizados", targetNamespace = "http://tempuri.org/")
        Boolean exibirFinalizados,
        @WebParam(name = "registrosPagina", targetNamespace = "http://tempuri.org/")
        Integer registrosPagina,
        @WebParam(name = "pagina", targetNamespace = "http://tempuri.org/")
        Integer pagina);

    /**
     * 
     * @param numeroVoo
     * @param pagina
     * @param exibirFinalizados
     * @param icao
     * @param registrosPagina
     * @param idioma
     * @param partida
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarVoosNumero", action = "http://tempuri.org/ConsultarVoosNumero")
    @WebResult(name = "ConsultarVoosNumeroResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarVoosNumero", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVoosNumero")
    @ResponseWrapper(localName = "ConsultarVoosNumeroResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVoosNumeroResponse")
    public String consultarVoosNumero(
        @WebParam(name = "icao", targetNamespace = "http://tempuri.org/")
        String icao,
        @WebParam(name = "idioma", targetNamespace = "http://tempuri.org/")
        String idioma,
        @WebParam(name = "partida", targetNamespace = "http://tempuri.org/")
        Boolean partida,
        @WebParam(name = "numeroVoo", targetNamespace = "http://tempuri.org/")
        String numeroVoo,
        @WebParam(name = "exibirFinalizados", targetNamespace = "http://tempuri.org/")
        Boolean exibirFinalizados,
        @WebParam(name = "registrosPagina", targetNamespace = "http://tempuri.org/")
        Integer registrosPagina,
        @WebParam(name = "pagina", targetNamespace = "http://tempuri.org/")
        Integer pagina);

    /**
     * 
     * @param idioma
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListarAeroportos", action = "http://tempuri.org/ListarAeroportos")
    @WebResult(name = "ListarAeroportosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListarAeroportos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarAeroportos")
    @ResponseWrapper(localName = "ListarAeroportosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarAeroportosResponse")
    public String listarAeroportos(
        @WebParam(name = "idioma", targetNamespace = "http://tempuri.org/")
        String idioma);

    /**
     * 
     * @param icao
     * @param idioma
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ListarCompanhias", action = "http://tempuri.org/ListarCompanhias")
    @WebResult(name = "ListarCompanhiasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListarCompanhias", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarCompanhias")
    @ResponseWrapper(localName = "ListarCompanhiasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListarCompanhiasResponse")
    public String listarCompanhias(
        @WebParam(name = "icao", targetNamespace = "http://tempuri.org/")
        String icao,
        @WebParam(name = "idioma", targetNamespace = "http://tempuri.org/")
        String idioma);

}
